"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CovalProvider } from "@coval-ai/components";

const token = process.env.NEXT_PUBLIC_COVAL_TOKEN || "";
const apiUrl = process.env.NEXT_PUBLIC_COVAL_API_URL || undefined;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CovalProvider token={token} apiUrl={apiUrl}>
          {children}
        </CovalProvider>
      </body>
    </html>
  );
}
